services:
  notebook-analyzer-web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=${DEBUG:-false}
      - SECRET_KEY=${SECRET_KEY:-}
      # LLM Enhancement (optional - leave empty to disable)
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-}
      # Repository access tokens (optional - leave empty for public repos only)
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GITLAB_TOKEN=${GITLAB_TOKEN:-}
      # Development environment flag (enables full transparency features)
      - NODE_ENV=development
      # Self-review feature (set to true to enable the valuable self-review functionality)
      - ENABLE_SELF_REVIEW=${ENABLE_SELF_REVIEW:-true}
    volumes:
      - /tmp:/tmp:rw
      # Mount source code for development (optional - comment out for production)
      - ./analyzer:/app/analyzer:ro
      - ./templates:/app/templates:ro
      - ./examples:/app/examples:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Resource limits for Docker
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Optional: Add nginx for production deployment
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
  #   depends_on:
  #     - notebook-analyzer-web
  #   restart: unless-stopped 
